OBJS = main.o callbacks.o 
CFLAGS = -Wall -Wextra 
LIBS = -lpspgu -lpspgum 
ASFLAGS = $(CFLAGS)

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = dindin
PSPSDK = /usr/psp/sdk
include $(PSPSDK)/lib/build.mak

