OBJS = main.o callbacks.o pgeFont.o graphics.o
CFLAGS = -Wall -Wextra 
LIBS = -lpspgu -lpspgum -lfreetype
ASFLAGS = $(CFLAGS)

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = dindin
PSPSDK = /usr/psp/sdk
include $(PSPSDK)/lib/build.mak

