TARGET=main
OBJS = ./src/main.o ./src/callbacks.o ./src/graphics.o
CFLAGS = -Wall -Wextra 
LIBS = -lpspgu -lpspgum -lm 

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Tilemaps
PSPSDK = /usr/psp/sdk
include $(PSPSDK)/lib/build.mak

